@FileShareAPI_HostAddress = http://localhost:5279/api

GET {{FileShareAPI_HostAddress}}/file/test
Accept: application/json

###

GET {{FileShareAPI_HostAddress}}/file
Accept: application/json

###

GET {{FileShareAPI_HostAddress}}/file/fbc35cc7-65b3-4603-b37a-5db343c98414
Accept: application/json
